services:
  postgres:
    image: postgres:15
    container_name: flight-api-db
    environment:
      POSTGRES_DB: flight
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432